using BE_Portfolio.DTOs.Profile;
using BE_Portfolio.Models.Documents;
using BE_Portfolio.Models.ValueObjects;
using BE_Portfolio.Persistence.Repositories.Interfaces;
using BE_Portfolio.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BE_Portfolio.Controllers.Admin;

[ApiController]
[Route("api/admin/profile")]
// [Authorize(Roles = "Admin")]
public class ProfileAdminController(IProfileRepository profileRepo, PortfolioService portfolioService) : ControllerBase
{
    [HttpGet]
    public async Task<ActionResult<Profile>> GetProfile(CancellationToken ct)
    {
        var profile = await profileRepo.GetProfileAsync(ct);
        if (profile == null)
        {
            profile = new Profile
            {
                FullName = "Your Name",
                Headline = "Your Headline",
                Location = "Your Location",
                About = "About You"
            };
            await profileRepo.UpdateProfileAsync(profile, ct);
        }
        return Ok(profile);
    }

    [HttpPut]
    public async Task<IActionResult> UpdateProfile([FromBody] UpdateProfileRequestDto dto, CancellationToken ct)
    {
        var profile = await profileRepo.GetProfileAsync(ct);
        if (profile == null)
        {
            profile = new Profile();
        }

        if (dto.FullName != null) profile.FullName = dto.FullName;
        if (dto.Headline != null) profile.Headline = dto.Headline;
        if (dto.Location != null) profile.Location = dto.Location;
        if (dto.About != null) profile.About = dto.About;
        if (dto.YearsExperience.HasValue) profile.YearsExperience = dto.YearsExperience.Value;
        if (dto.ProjectsCompleted.HasValue) profile.ProjectsCompleted = dto.ProjectsCompleted.Value;
        if (dto.Coffees.HasValue) profile.Coffees = dto.Coffees.Value;

        if (dto.SocialLinks != null)
        {
            profile.SocialLinks = dto.SocialLinks.Select(s => new SocialLink
            {
                Platform = s.Platform,
                Url = s.Url,
                Order = s.Order
            }).ToList();
        }

        await profileRepo.UpdateProfileAsync(profile, ct);
        return Ok(profile);
    }

    [HttpPost("avatar")]
    public async Task<IActionResult> UploadAvatar(IFormFile file, CancellationToken ct)
    {
        var profile = await profileRepo.GetProfileAsync(ct);
        if (profile == null)
        {
            // Ensure profile exists before attaching image
            profile = new Profile { FullName = "New Profile" };
            await profileRepo.UpdateProfileAsync(profile, ct);
            // Re-fetch to get ID if generated by DB (though usually client generated or Guid, but Mongo uses ObjectId)
            // Actually UpsertAsync uses doc.Id. If doc.Id is empty, it might be issue.
            // BaseDocument usually initializes Id.
        }

        await portfolioService.SetProfileImageAsync(profile.Id, file, ct);
        
        // Fetch updated profile to return new AvatarUrl
        var updated = await profileRepo.GetProfileAsync(ct);
        return Ok(new { Url = updated?.AvatarUrl });
    }
}
